# Generated by Django 4.0.5 on 2022-07-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('member', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('alternate_contact_no', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('total_vehicle', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Digital_app.registered_user')),
            ],
        ),
    ]
